{{- if eq .Values.database.type "internal" -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config
  labels:
    app: postgresql
    {{- include "concord.commonLabels" . | nindent 4 }}
data:
  POSTGRES_DB: {{ .Values.database.internal.database }}
  POSTGRES_USER: {{ .Values.database.internal.user }}
  PGDATA: /concord/postgresql/data
{{- end -}}
