{{- if eq .Values.database.type "internal" -}}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql-pvc
  labels:
    app: postgresql
spec:
{{- if .Values.database.storageClass }}
{{- if (eq "-" .Values.database.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}
{{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      {{- if .Values.database.storageSize }}
      storage: "{{ .Values.database.storageSize }}"
      {{- else }}
      storage: 2Gi
      {{- end }}
{{- end -}}
