{{- if eq .Values.database.type "internal" -}}
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: postgresql
    {{- include "concord.commonLabels" . | nindent 4 }}
spec:
  type: {{ .Values.database.internal.serviceType }}
  ports:
  - port: {{ .Values.database.internal.port }}
    protocol: TCP
  selector:
    app: postgresql
{{- end -}}
