{{ define "concord.db" }}
  DB_PASSWORD: {{ .Db.password }}
  SERVER_PASSWORD_BASE64: {{ .Values.server.serverPassword | default .Db.password | b64enc }}
  SECRET_STORE_SALT_BASE64: {{ .Values.server.serverPassword | default .Db.password | b64enc }}
  PROJECT_SECRET_SALT_BASE64: {{ .Values.server.serverPassword | default .Db.password | b64enc }}
  ADMIN_TOKEN: {{ .Values.server.adminToken }}
  AGENT_TOKEN: {{ .Values.server.agentToken }}
  {{- if .Values.ldap.enabled }}
  LDAP_SYSTEM_PASSWORD: {{ .Values.ldap.systemPassword }}
  {{- end }}
  {{- if .Values.github.enabled }}
  GITHUB_SECRET: {{ .Values.github.secret }}
  {{- end }}
  {{- if .Values.git }}{{- if .Values.git.oauth }}
  GIT_OAUTH: {{ .Values.git.oauth }}
  {{- end }}{{- end }}
{{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: concord-server-credentials
type: Opaque
stringData:
  {{- if eq .Values.database.type "internal" }}
    {{- include "concord.db" (dict "Values" .Values "Db" .Values.database.internal) }}
  {{- else if eq .Values.database.type "external" }}
    {{- include "concord.db" (dict "Values" .Values "Db" .Values.database.external) }}
  {{- end }}
