{{ define "concord.db" }}
  {{- if .Db.password }}
  DB_PASSWORD: {{ .Db.password | quote }}
  {{- end }}
  {{- if .Values.server.serverPassword | default .Db.password }}
  SERVER_PASSWORD_BASE64: {{ .Values.server.serverPassword | default .Db.password | b64enc | quote }}
  SECRET_STORE_SALT_BASE64: {{ .Values.server.serverPassword | default .Db.password | b64enc | quote }}
  PROJECT_SECRET_SALT_BASE64: {{ .Values.server.serverPassword | default .Db.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.server.adminToken }}
  ADMIN_TOKEN: {{ .Values.server.adminToken | quote }}
  {{- end }}
  {{- if .Values.server.agentToken }}
  AGENT_TOKEN: {{ .Values.server.agentToken | quote }}
  {{- end }}
  {{- if .Values.ldap.enabled }}
  LDAP_SYSTEM_PASSWORD: {{ .Values.ldap.systemPassword | quote }}
  {{- end }}
  {{- if .Values.github.enabled }}
  GITHUB_SECRET: {{ .Values.github.secret | quote }}
  {{- end }}
  {{- if .Values.git }}{{- if .Values.git.oauth }}
  GIT_OAUTH: {{ .Values.git.oauth | quote }}
  {{- end }}{{- end }}
  {{- range $key, $val := .Values.server.extraSecrets }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: concord-server-credentials
type: Opaque
stringData:
  {{- if eq .Values.database.type "internal" }}
    {{- include "concord.db" (dict "Values" .Values "Db" .Values.database.internal) }}
  {{- else if eq .Values.database.type "external" }}
    {{- include "concord.db" (dict "Values" .Values "Db" .Values.database.external) }}
  {{- end }}
