{{ define "concord.db" }}
  DB_PASSWORD: {{ .Db.password | b64enc }}
  ADMIN_TOKEN: {{ .Values.server.adminToken | b64enc }}
  AGENT_TOKEN: {{ .Values.server.agentToken | b64enc }}
  {{- if .Values.ldap.enabled }}
  LDAP_SYSTEM_PASSWORD: {{ .Values.ldap.systemPassword | b64enc }}
  {{- end }}
  {{- if .Values.github.enabled }}
  GITHUB_SECRET: {{ .Values.github.secret | b64enc }}
  {{- end }}
  {{- if .Values.git }}{{- if .Values.git.oauth }}
  GIT_OAUTH: {{ .Values.git.oauth | b64enc }}
  {{- end }}{{- end }}
{{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: concord-server-credentials
type: Opaque
data:
  {{- if eq .Values.database.type "internal" }}
    {{- include "concord.db" (dict "Values" .Values "Db" .Values.database.internal) }}
  {{- else if eq .Values.database.type "external" }}
    {{- include "concord.db" (dict "Values" .Values "Db" .Values.database.external) }}
  {{- end }}
