concord-agent {
  capabilities = {
    flavor: "kubernetes"
    k8s: {
      cluster: "default"
      namespace: "{{ .Values.Namespace }}"
      pod = ${MY_POD_NAME}
    }
  }

  workersCount = 1

  prefork {
    maxAge = "30 seconds"
    maxCount = 1
  }

  maintenanceModeListenerHost = "0.0.0.0"

  server {
    # TODO use HTTPS and WSS for communications between the Server and agents

    {{ if eq .Values.server.type "internal" }}
    apiBaseUrl: "http://concord-server:{{ .Values.expose.port }}"
    websocketUrl: "ws://concord-server:{{ .Values.expose.port }}/websocket"
    {{ else }}
    apiBaseUrl: "{{ .Values.server.apiBaseUrl }}"
    websocketUrl: "{{ .Values.server.websocketUrl }}"
    {{ end }}

    readTimeout = "{{ .Values.agent.readTimeout }}"
    apiKey = "{{ .Values.server.agentToken }}"
  }

  {{ if .Values.git }}{{ if .Values.git.oauth }}
  git {
    oauth = "{{ .Values.git.oauth }}"
  }
  {{ end }}{{ end }}

  {{ if .Values.github }}{{ if .Values.github.appInstallation }}{{ if .Values.github.appInstallation.enabled }}
  github {
    appInstallation {
      auth = [
        {{- range $index, $auth := .Values.github.appInstallation.auth }}
        {
          id = "{{ $auth.id }}"
          type = "{{ $auth.type }}"
          urlPattern = "{{ $auth.urlPattern }}"
          {{- if $auth.username }}
          username = "{{ $auth.username }}"
          {{- end }}
          {{- if $auth.apiUrl }}
          apiUrl = "{{ $auth.apiUrl }}"
          {{- end }}
          {{- if eq $auth.type "GITHUB_APP_INSTALLATION" }}
          clientId = "{{ $auth.clientId }}"
          privateKey = "/opt/concord/conf/github-app-keys/{{ $auth.privateKeyFile }}"
          {{- end }}
          {{- if eq $auth.type "OAUTH_TOKEN" }}
          token = "{{ $auth.token }}"
          {{- end }}
        }
        {{- end }}
      ]
      {{- with .Values.github.appInstallation.httpClientTimeout }}
      httpClientTimeout = "{{ . }}"
      {{- end }}
      {{- with .Values.github.appInstallation.systemAuthCacheDuration }}
      systemAuthCacheDuration = "{{ . }}"
      {{- end }}
      {{- with .Values.github.appInstallation.systemAuthCacheMaxWeight }}
      systemAuthCacheMaxWeight = {{ . }}
      {{- end }}
    }
  }
  {{ end }}{{ end }}{{ end }}
}
