{{- if eq .Values.server.type "internal" -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: concord-server
  {{- if .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml .Values.deploymentAnnotations | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      app: concord-server
  template:
    metadata:
      labels:
        app: concord-server
      {{- if .Values.podAnnotations }}
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- include "imagePullSecretName" . | nindent 6 }}
      # https://medium.com/@xcoulon/initializing-containers-in-order-with-kubernetes-18173b9cc222
      initContainers:
      {{- if eq .Values.database.type "internal" }}
        - name: postgres-ready
          image: {{ .Values.database.internal.image.repository }}:{{ .Values.database.internal.image.tag }}
          command: [ 'sh', '-c', 'until pg_isready -h postgresql -p 5432; do echo waiting for database; sleep 1; done; sleep 5;' ]
      {{- end }}
      {{- range $index, $sidecar := .Values.sidecars }}
      {{- if $sidecar.enabled }}
        - name: {{ $sidecar.name }}
          image: {{ $sidecar.image }}
          command: [ 'sh', '-c', 'ls /{{ $sidecar.name }}/ && cp /dist/* /{{ $sidecar.name }}/' ]
          volumeMounts:
            - name: {{ $sidecar.name }}-jars
              mountPath: /{{ $sidecar.name }}/
      {{- end }}
      {{- end }}
      containers:
        - name: concord-server
          {{- if .Values.serverImageOverride }}
          image: {{ .Values.serverImageOverride }}
          {{- else }}
          image: {{ .Values.registry }}/{{ .Values.serverImageName }}:{{ .Values.version }}
          {{- end }}
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          volumeMounts:
            - name: concord-server-volume
              mountPath: /opt/concord/tmp
            - name: cfg
              mountPath: "/opt/concord/conf/server.conf"
              subPath: server.conf
            - name: cfg
              mountPath: "/opt/concord/conf/mvn.json"
              subPath: mvn.json
            - name: cfg
              mountPath: "/opt/concord/console/cfg.js"
              subPath: cfg.js
            {{- range $index, $sidecar := .Values.sidecars }}
            {{- if $sidecar.enabled }}
            - name: {{ $sidecar.name }}-jars
              mountPath: {{ $sidecar.name }}
            {{- end }}
            {{- end }}
          ports:
            - containerPort: 8001
          readinessProbe:
            httpGet:
              port: 8001
              path: /api/v1/server/ping
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 5
          env:
            - name: CONCORD_TMP_DIR
              value: "/opt/concord/tmp"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: concord-server-credentials
                  key: DB_PASSWORD
            - name: SERVER_PASSWORD_BASE64
              valueFrom:
                secretKeyRef:
                  name: concord-server-credentials
                  key: SERVER_PASSWORD_BASE64
            - name: SECRET_STORE_SALT_BASE64
              valueFrom:
                secretKeyRef:
                  name: concord-server-credentials
                  key: SECRET_STORE_SALT_BASE64
            - name: PROJECT_SECRET_SALT_BASE64
              valueFrom:
                secretKeyRef:
                  name: concord-server-credentials
                  key: PROJECT_SECRET_SALT_BASE64
            - name: ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: concord-server-credentials
                  key: ADMIN_TOKEN
            - name: AGENT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: concord-server-credentials
                  key: AGENT_TOKEN
            - name: LDAP_SYSTEM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: concord-server-credentials
                  key: LDAP_SYSTEM_PASSWORD
                  optional: true
            - name: GITHUB_SECRET
              valueFrom:
                secretKeyRef:
                  name: concord-server-credentials
                  key: GITHUB_SECRET
                  optional: true
            - name: GIT_OAUTH
              valueFrom:
                secretKeyRef:
                  name: concord-server-credentials
                  key: GIT_OAUTH
                  optional: true
            - name: CONCORD_CFG_FILE
              value: /opt/concord/conf/server.conf
            - name: CONCORD_MAVEN_CFG
              value: "/opt/concord/conf/mvn.json"
            - name: EXTRA_CLASSPATH
              value: "{{- range $index, $sidecar := .Values.sidecars -}}
                      {{- if $sidecar.enabled -}}
                      {{- if $index }}:{{ end }}/{{ $sidecar.name }}/*
                      {{- end -}}
                      {{- end }}"
            {{- range $key, $val := .Values.server.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
            {{- if .Values.server.env }}
            {{- toYaml .Values.server.extraEnv | nindent 12 }}
            {{- end}}
          {{- if .Values.serverResources }}
          resources:
            {{- toYaml .Values.serverResources | nindent 12 }}
          {{- end }}
      volumes:
        - name: concord-server-volume
          emptyDir:
            sizeLimit: {{ .Values.server.tmpDirSizeLimit }}
        - name: cfg
          configMap:
            name: server-cfg
        {{- range $s := .Values.sidecars }}
        {{- if $s.enabled }}
        - name: {{ $s.name }}-jars
          emptyDir: { }
        {{- end }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}
