---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: concord-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: concord-server
  template:
    metadata:
      labels:
        app: concord-server
    spec:
      {{- include "imagePullSecretName" . | nindent 6 }}
      containers:
        - name: concord-server
          image: {{ .Values.registry }}/{{ .Values.serverImageName }}:{{ .Values.version }}
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          volumeMounts:
          - name: "cfg"
            mountPath: "/opt/concord/conf/server.conf"
            subPath: server.conf
          {{ if .Values.oidc.enabled }}
          - name: "cfgjs"
            mountPath: "/opt/concord/console/cfg.js"
            subPath: cfg.js
          {{ end }}
          ports:
          - containerPort: 8001
          env:
          - name: CONCORD_CFG_FILE
            value: /opt/concord/conf/server.conf
      volumes:
        - name: cfg
          configMap:
            name: server-conf
        {{ if .Values.oidc.enabled }}
        - name: cfgjs
          configMap:
            name: cfg-js
        {{ end }}
