---
apiVersion: v1
kind: ConfigMap
metadata:
  name: concord-cfg
data:
{{ (tpl (.Files.Glob "files/agent/agent.conf").AsConfig . ) | indent 2 }}
{{ (tpl (.Files.Glob "files/agent/mvn.json").AsConfig . ) | indent 2 }}
