name: Stateless Helm Chart build
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Helm Setup
        uses: azure/setup-helm@v1
        with:
          version: 3.8.0

      - name: Lint Helm Charts
        run: |
          helm lint concord/

      - name: Package Helm Charts
        run: |
          helm package concord/ --version ${GITHUB_REF_NAME}

      - name: Publish Helm Charts
        run: |
          helm push stateless-${GITHUB_REF_NAME}.tgz "oci://${CONTAINER_REGISTRY}"
